classdef demoAppsTest < matlab.unittest.TestCase
    %DEMOAPPSTEST Verifies the packaged App Designer demonstration apps.

    properties (TestParameter)
        DemoName = struct( ...
            uiaxesm_demo="uiaxesm_demo", ...
            uibubblecloud_demo="uibubblecloud_demo", ...
            uiconfusionchart_demo="uiconfusionchart_demo", ...
            uigeobubble_demo="uigeobubble_demo", ...
            uiheatmap_demo="uiheatmap_demo", ...
            uimapaxes_demo="uimapaxes_demo", ...
            uiorthosliceviewer_demo="uiorthosliceviewer_demo", ...
            uiparallelplot_demo="uiparallelplot_demo", ...
            uipattern_demo="uipattern_demo", ...
            uipolaraxes_demo="uipolaraxes_demo", ...
            uiscatterhistogram_demo="uiscatterhistogram_demo", ...
            uisliceviewer_demo="uisliceviewer_demo", ...
            uismithplot_demo="uismithplot_demo", ...
            uivolshow_demo="uivolshow_demo", ...
            uiwordcloud_demo="uiwordcloud_demo")
    end

    properties (SetAccess = private)
        ProjectRoot (1, 1) string
    end

    methods (TestClassSetup)
        function setUpDemoPath(testCase)
            testCase.ProjectRoot = string( ...
                fileparts(fileparts(mfilename("fullpath"))));
            testCase.applyFixture( ...
                matlab.unittest.fixtures.PathFixture( ...
                testCase.ProjectRoot));
            setupPanelWrappedComponents;
        end
    end

    methods (Test)
        function testEmbeddedClassMatchesFilename( ...
                testCase, DemoName)
            codeText = demoAppsTest.readCode( ...
                testCase.ProjectRoot, DemoName);
            classToken = regexp( ...
                codeText, "^classdef\s+(\w+)", "tokens", "once");

            testCase.verifyEqual(string(classToken{1}), DemoName);
        end

        function testHasNoMachineSpecificPaths(testCase, DemoName)
            codeText = demoAppsTest.readCode( ...
                testCase.ProjectRoot, DemoName);
            machineSpecificPath = regexp( ...
                codeText, ...
                "(?i)([A-Z]:\\Users\\|/Users/[^/]+/)", ...
                "match");

            testCase.verifyEmpty(machineSpecificPath);
        end

        function testOnlyGeneratedAnalyzerAdvisoryRemains( ...
                testCase, DemoName)
            demoFile = fullfile( ...
                testCase.ProjectRoot, DemoName + ".mlapp");
            issues = checkcode(char(demoFile), "-id", "-struct");
            issueIds = string({issues.id});

            testCase.verifyTrue(all(issueIds == "INUSD"));
            testCase.verifyLessThanOrEqual(numel(issues), 1);
        end
    end

    methods (Test, TestTags = ["Integration", "Slow"])
        function testRuntimeLaunch(testCase, DemoName)
            app = feval(DemoName);
            testCase.addTeardown(@() delete(app));
            app.UIFigure.Visible = "off";
            drawnow;

            testCase.verifyEqual(string(class(app)), DemoName);
            testCase.verifyTrue(isvalid(app.UIFigure));
        end
    end

    methods (Static, Access = private)
        function codeText = readCode(projectRoot, demoName)
            demoFile = fullfile(projectRoot, demoName + ".mlapp");
            reader = appdesigner.internal.serialization.FileReader( ...
                char(demoFile));
            codeText = string(readMATLABCodeText(reader));
        end
    end
end
